# Generated by Django 6.0 on 2025-12-31 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="year",
            field=models.IntegerField(default=2020),
            preserve_default=False,
        ),
    ]
