# Generated by Django 6.0 on 2026-01-02 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("devtools", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Idea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("image", models.ImageField(blank=True, null=True, upload_to="ideas/")),
                ("content", models.CharField(max_length=100)),
                ("interest", models.IntegerField(default=0)),
                (
                    "devtool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ideas",
                        to="devtools.devtool",
                    ),
                ),
            ],
        ),
    ]
